Repository gruvat/projetct-myMusic-toTal, pull requests merged in 2022-08, with the labels that each got.

#25 Boot 463 - Refactoring repositories
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/repository/ArtistRepository.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/repository/MusicRepository.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/MusicServiceImpl.java
  MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/repository/ArtistRepositoryTest.java
  MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/repository/MusicRepositoryTest.java
  MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/service/MusicServiceTest.java
Labels: enhancement

#27 Collections with automatic token
  doc/Postman collection/MyMusic.postman_collection.json
Labels: enhancement

#28 Boot 501 and 502 - Implementing Playlist entity and repository
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/entity/Playlist.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/repository/PlaylistRepository.java
Labels: enhancement

#29 Boot 503 - PlaylistService implemented
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/service/MusicNotFoundException.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/service/PlaylistNotFoundException.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/PlaylistService.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/PlaylistServiceImpl.java
Labels: enhancement

#30 Boot 505 - Implementing DTOs and validation of request body
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/ExceptionHandlerConstraints.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/dto/ValidationErrorDto.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/request/RequestMusicsData.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/controller/TesteController.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/controller/dto/ArtistDto.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/controller/dto/MusicDto.java
Labels: enhancement

#31 Boot 506 - Implementing cache to Music endpoint
  MyMusic/pom.xml
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/SummitBootcampApplication.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/config/CachingConfig.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/MusicServiceImpl.java
  MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/service/MusicServiceCachingTest.java
Labels: enhancement

#33 [Fix] Boot 506 - Removing music name in creating object for test case
  MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/service/MusicServiceCachingTest.java
Labels: bug

#35 Boot 505 - Using default error format for request body validation
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/ExceptionHandlerConstraints.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/dto/ValidationErrorDto.java
Labels: enhancement

#37 [BOOT-582] Implementing log rolling files and adding missing logs and BOOT[505] Fixing bug from request body validation
  MyMusic/pom.xml
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/ExceptionHandlerConstraints.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/MusicServiceImpl.java
  MyMusic/src/main/resources/application.properties
  MyMusic/src/main/resources/log4j2.xml
Labels: bug, enhancement

#39 Boot 504 - PlaylistServiceTests implemented and validated | Boot 508 …
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/ExceptionHandlerConstraints.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/controller/ExceptionHandlerController.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/dto/ValidationErrorDto.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/dto/ValidationErrorWithFieldsDto.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/controller/MusicController.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/controller/PlaylistController.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/controller/TesteController.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/controller/dto/MusicDto.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/entity/Artist.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/entity/Music.java
Labels: enhancement

#40 Boot 584 - validating body; fixing minor issues
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/controller/ExceptionHandlerController.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/dto/ValidationErrorDto.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/dto/ValidationErrorWithFieldsDto.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/controller/PlaylistController.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/MusicService.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/PlaylistService.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/TokenService.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/TokenServiceImpl.java
  MyMusic/src/main/resources/application.properties
Labels: enhancement

#41 [BOOT-508] Improving music service unit tests
  MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/service/MusicServiceTest.java
Labels: enhancement

#42 Boot 510 - findMusicsByPlaylistId method implemented
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/controller/MusicController.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/controller/PlaylistController.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/repository/MusicRepository.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/repository/PlaylistRepository.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/PlaylistService.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/PlaylistServiceImpl.java
  MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/repository/MusicRepositoryTest.java
  doc/Postman collection/MyMusic.postman_collection.json
Labels: enhancement

#43 Boot 585 - 404 error handled; emojis added to logs and exceptions
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/controller/ExceptionHandlerController.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/service/CredentialsException.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/service/InvalidParameterException.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/service/MusicNotFoundException.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/service/MusicsAndArtistsNotFoundException.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/service/PlaylistNotFoundException.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/service/RequestTokenProviderApiException.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/controller/MusicController.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/controller/PlaylistController.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/MusicServiceImpl.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/PlaylistServiceImpl.java
  MyMusic/src/main/resources/application.properties
  MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/service/MusicServiceTest.java
  MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/service/PlaylistServiceTest.java
Labels: enhancement

#44 Boot 643 - deleteMusicFromPlaylist methods added
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/service/MusicNotFoundInPlaylistException.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/PlaylistService.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/PlaylistServiceImpl.java
  MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/service/PlaylistServiceTest.java
Labels: enhancement

#45 Boot 645 - deleteMusicFromPlaylist methods added on controller
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/controller/PlaylistController.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/PlaylistService.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/PlaylistServiceImpl.java
  doc/Postman collection/MyMusic.postman_collection.json
Labels: enhancement

#46 Boot 638 - logs missing added
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/TokenServiceImpl.java
Labels: enhancement

#50 [Fix] Boot 376 and 507 - TokenService getting TokenProvider path from env file
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/TokenServiceImpl.java
Labels: bug, enhancement

#49 [BOOT-634] Refactoring service tests using mockito
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/entity/Playlist.java
  MyMusic/src/main/resources/log4j2.xml
  MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/service/MusicServiceTest.java
  MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/service/PlaylistServiceTest.java
Labels: enhancement

#51 [BOOT-644] Refactoring repository test using @DataJpaTest and h2 database
  MyMusic/pom.xml
  MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/repository/MusicRepositoryTest.java
  MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/service/MusicServiceCachingTest.java
  MyMusic/src/test/resources/application-repository.properties
  MyMusic/src/test/resources/data.sql
Labels: enhancement

#53 Boot 635 - Updating readme
  MyMusic/README.md
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/config/SwaggerConfig.java
  README.md
  TokenProvider/README.md
Labels: documentation

#54 BOOT 639 - Jacoco implemented
  MyMusic/pom.xml
Labels: enhancement

#56 Bugfix/dto
  MyMusic/pom.xml
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/controller/dto/MusicDto.java
Labels: bug

#58 [BOOT-642] Swagger documentation
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/config/SwaggerConfig.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/controller/MusicController.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/controller/PlaylistController.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/controller/dto/ArtistDto.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/controller/dto/MusicDto.java
Labels: documentation

#57 Boot 636 - Integration tests for TokenService class
  MyMusic/pom.xml
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/TokenServiceImpl.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/util/Base64Token.java
  MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/service/TokenServiceTest.java
  MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/service/util/Base64TokenTest.java
Labels: enhancement

#59 [Fix] Improvement in Jacoco branch coverage by creation of new test cases
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/TokenServiceImpl.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/util/Base64Token.java
  MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/service/TokenServiceTest.java
  MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/service/util/Base64TokenTest.java
Labels: bug, enhancement

#61 Adding collection updated
  MyMusic/pom.xml
  doc/Postman collection/MyMusic.postman_collection.json
Labels: documentation, enhancement

#62 Adding postman env
  doc/Postman collection/token-provider.postman_environment.json
Labels: documentation, enhancement
