Repository gruvat/projetct-myMusic-toTal, pull requests merged in 2022-07, with the labels that each got.

#2 Creation of JUnit Action workflow
  .github/workflows/unit-test-workflow.yml
Labels: Automation

#1 Boot 364 - Criação de Entity Artista
  MyMusic/pom.xml
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/entity/Artista.java
  MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/SummitBootcampApplicationTests.java
Labels: enhancement

#9 Boot 367 - Alteração na implementação da Repository | Testes unitário…
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/entity/Artista.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/entity/Musica.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/repository/ArtistaRepository.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/repository/ArtistaRepositoryImpl.java
  MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/repository/ArtistaRepositoryTest.java
Labels: enhancement

#15 Boot 374 -Token authentication
  MyMusic/README.md
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/MissingCredentialsException.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/RequestTokenProviderException.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/security/SecurityConfig.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/security/Token/TokenDTO.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/security/Token/TokenInterceptor.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/TokenService.java
  MyMusic/src/main/resources/application.properties
Labels: enhancement

#16 Exception handling in TokenProvider calls and Postmand collection
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/CredentialsException.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/MissingCredentialsException.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/RequestTokenProviderApiException.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/RequestTokenProviderException.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/TokenService.java
  doc/Postman collection/MyMusic.postman_collection.json
Labels: documentation, enhancement

#17 Boot 372 - Exceptions handling
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/ErrorResponse.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/controller/MusicControllerExceptionHandler.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/service/InvalidParameterException.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/service/MusicsAndArtistsNotFoundException.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/controller/MusicController.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/MusicService.java
  MyMusic/src/main/resources/application.properties
Labels: enhancement

#18 Boot 372 - Response HttpStatus annotation included to custom exceptions
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/CredentialsException.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/service/CredentialsException.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/service/RequestTokenProviderApiException.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/TokenService.java
Labels: enhancement

#22 Update README.md
  MyMusic/README.md
Labels: documentation

#21 Controller refactoring
  MyMusic/pom.xml
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/ErrorResponse.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/controller/MusicControllerExceptionHandler.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/service/CredentialsException.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/service/MusicsAndArtistsNotFoundException.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/common/exception/service/RequestTokenProviderApiException.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/controller/MusicController.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/controller/dto/ArtistDto.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/controller/dto/MusicDto.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/entity/Artist.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/security/SecurityConfig.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/MusicService.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/MusicServiceImpl.java
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/TokenService.java
  MyMusic/src/main/resources/application.properties
  MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/service/MusicServiceTest.java
Labels: enhancement

#24 [Fix] Boot 461 - Application checking if username and password are not blank
  MyMusic/src/main/java/com/ciandt/summit/bootcamp2022/service/TokenService.java
Labels: bug
